'use client';
import {useEffect,useState} from 'react';
type C={id:string;name:string;about:string;category:string;members:number};type T={id:string;community:string;title:string;author:string;replies:string[]};type S={id:string;from:string;body:string};
const initialC:C[]=[{id:'eu-amo-os-anos-2000',name:'Eu amo os anos 2000',about:'Se você viveu a era do MSN, do CD e da internet discada, esse é seu lugar!',category:'Entretenimento',members:15982},{id:'odeio-acordar-cedo',name:'Odeio acordar cedo',about:'Só mais cinco minutinhos...',category:'Humor',members:9834},{id:'internet-discada',name:'Internet discada',about:'Aquele barulho de modem inesquecível.',category:'Computadores e Internet',members:7244},{id:'musica-boa',name:'Música boa não tem idade',about:'Compartilhe suas músicas favoritas.',category:'Música',members:12092},{id:'lan-house',name:'Saudades das lan houses',about:'CS 1.6, Ragnarok e tardes inteiras jogando!',category:'Jogos',members:4681}];
const initialT:T[]=[{id:'nick-msn',community:'eu-amo-os-anos-2000',title:'Qual era seu nick no MSN?',author:'Mariana',replies:['Eu usava frases de música no nick 😂','E os subnicks? Que saudade!']},{id:'depoimentos',community:'eu-amo-os-anos-2000',title:'Depoimentos que a gente nunca apagava',author:'Rafael',replies:['E tinha que aceitar para aparecer!']},{id:'modem',community:'internet-discada',title:'Quem lembra do som da conexão?',author:'Bruno',replies:['Não podia usar o telefone ao mesmo tempo.']}];
const initialS:S[]=[{id:'1',from:'Mariana Oliveira',body:'Passando pra deixar um scrap! Saudades de você 💜'},{id:'2',from:'Rafael Costa',body:'Quando der passa na minha página. Abraço!'}];
const friendNames=['Mariana Oliveira','Rafael Costa','Ana Beatriz','Bruno Lima','Juliana Martins','Lucas Santos','Carolina Dias','Felipe Rocha','Camila Alves'];
const makeId=()=>String(Date.now())+Math.random().toString(36).slice(2,6);
function read<T>(k:string,def:T):T{try{const v=localStorage.getItem(k);return v?JSON.parse(v):def}catch{return def}}
function save(k:string,v:unknown){localStorage.setItem(k,JSON.stringify(v))}
function Box({title,children,more}:{title?:string;children:React.ReactNode;more?:React.ReactNode}){return <section className="classic-box">{title&&<div className="box-title"><b>{title}</b>{more}</div>}{children}</section>}
function Portrait({name,large=false}:{name:string;large?:boolean}){return <span className={'portrait '+(large?'large':'')}>{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>}
const path=(segments:string[])=>'/'+segments.join('/');
export default function Classic(){const [route,setRoute]=useState('/'),[cs,setCs]=useState<C[]>(initialC),[ts,setTs]=useState<T[]>(initialT),[scraps,setScraps]=useState<S[]>(initialS),[joined,setJoined]=useState<string[]>(['eu-amo-os-anos-2000','internet-discada']),[profile,setProfile]=useState({name:'Meu perfil',city:'Brasil',about:'De volta aos bons tempos da internet!'}),[draft,setDraft]=useState(''),[topicTitle,setTopicTitle]=useState(''),[search,setSearch]=useState(''),[newName,setNewName]=useState(''),[newAbout,setNewAbout]=useState(''),[tab,setTab]=useState('social'),[ready,setReady]=useState(false);
useEffect(()=>{setRoute(location.pathname);setCs(read('iogurte-c',initialC));setTs(read('iogurte-t',initialT));setScraps(read('iogurte-s',initialS));setJoined(read('iogurte-j',['eu-amo-os-anos-2000','internet-discada']));setProfile(read('iogurte-p',{name:'Meu perfil',city:'Brasil',about:'De volta aos bons tempos da internet!'}));setReady(true);const pop=()=>{setRoute(location.pathname);setDraft('')};addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
useEffect(()=>{if(!ready)return;save('iogurte-c',cs);save('iogurte-t',ts);save('iogurte-s',scraps);save('iogurte-j',joined);save('iogurte-p',profile)},[ready,cs,ts,scraps,joined,profile]);
function go(p:string){history.pushState(null,'',p);setRoute(p);setDraft('');setTopicTitle('');window.scrollTo(0,0)}
function A({to,children}:{to:string;children:React.ReactNode}){return <a href={to} onClick={e=>{e.preventDefault();go(to)}}>{children}</a>}
const parts=route.split('/').filter(Boolean),where=parts[0]||'home',cid=parts[1],tid=parts[3],community=cs.find(x=>x.id===cid),topic=ts.find(x=>x.id===tid),user=parts[1]||'me';
function postScrap(){if(!draft.trim())return;setScraps(s=>[{id:makeId(),from:profile.name,body:draft.trim()},...s]);setDraft('')}
function createCommunity(){if(!newName.trim())return;const id=makeId();setCs(v=>[{id,name:newName.trim(),about:newAbout.trim()||'Nova comunidade',category:'Outros',members:1},...v]);setJoined(v=>[...v,id]);setNewName('');setNewAbout('');go('/communities/'+id)}
function createTopic(){if(!topicTitle.trim()||!community)return;const id=makeId();setTs(v=>[{id,community:community.id,title:topicTitle.trim(),author:profile.name,replies:[]},...v]);go('/communities/'+community.id+'/topic/'+id)}
const people=<div className="thumb-grid">{friendNames.map((n,i)=><button onClick={()=>go('/profile/'+i)} key={n}><Portrait name={n}/><small>{n.split(' ')[0]}</small></button>)}</div>;
const smallCs=<div className="thumb-grid">{cs.slice(0,6).map(c=><button onClick={()=>go('/communities/'+c.id)} key={c.id}><span className="community-avatar">{c.name.slice(0,2)}</span><small>{c.name}</small></button>)}</div>;
return <><header className="topbar"><div className="topinside"><A to="/"><span className="logo">iogurte<span>✳</span></span></A><nav><A to="/">início</A><A to="/profile/me">perfil</A><A to="/scraps">recados</A><A to="/friends">amigos</A><A to="/communities">comunidades</A></nav><span className="topright">Olá, {profile.name} · <A to="/settings">configurações</A></span></div></header><div className="classic-layout"><aside className="leftcol"><div className="user-card"><div className="picture"><Portrait name={profile.name} large/></div><b><A to="/profile/me">{profile.name}</A></b><small>Brasil<br/>online 🟢</small><div className="side-links">{[['🏠','início','/'],['👤','perfil','/profile/me'],['✉','recados','/scraps'],['📷','fotos','/photos'],['💬','depoimentos','/testimonials'],['👥','amigos','/friends'],['▦','comunidades','/communities'],['⚙','configurações','/settings']].map(([icon,name,to])=><A key={to} to={to}>{icon} {name}</A>)}</div></div><Box title="meu perfil"><div className="small-pad">☀ confiável &nbsp; ♥ legal<br/>★ sexy<br/><A to="/settings">editar perfil</A></div></Box></aside>
<main className="centercol">
{where==='home'&&<><div className="mainhead"><h1>Bem-vindo(a), {profile.name}!</h1><p>O lugar onde as amizades e comunidades fazem a diferença.</p><div className="quick-stats"><A to="/scraps">✉ recados <strong>{scraps.length}</strong></A><A to="/friends">👥 amigos <strong>128</strong></A><A to="/communities">▦ comunidades <strong>{joined.length}</strong></A><A to="/testimonials">💬 depoimentos <strong>1</strong></A></div><p>visualizações do perfil: desde o início: <b>2.841</b> | semana passada: <b>14</b></p><p><b>Sorte de hoje:</b> As melhores amizades são para sempre.</p></div><Box title="próximos aniversários"><div className="birthday-row">{friendNames.slice(0,4).map((n,i)=><div key={n}><Portrait name={n}/><span>{n.split(' ')[0]}<br/>{i+10} de outubro</span></div>)}</div></Box><Box title="atualizações dos meus amigos">{['Mariana atualizou sua foto de perfil','Rafael entrou na comunidade Eu amo os anos 2000','Bruno começou uma discussão em Internet discada'].map(s=><p className="activity" key={s}>✦ {s}</p>)}</Box><Box title="últimos recados" more={<A to="/scraps">ver todos »</A>}>{scraps.slice(0,2).map(s=><div className="listline" key={s.id}><b>{s.from}</b><p>{s.body}</p></div>)}</Box></>}
{where==='profile'&&<><div className="mainhead"><h1>{user==='me'?profile.name:friendNames[Number(user)]||'Perfil de amigo'}</h1><div className="quick-stats"><A to="/scraps">recados ({scraps.length})</A><A to="/friends">amigos (128)</A><A to="/testimonials">depoimentos (1)</A></div><p>☀ confiável &nbsp; ♥ legal &nbsp; ★ sexy</p></div><Box title="informações do perfil"><div className="tabs">{['social','profissional','pessoal'].map(t=><button className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><table className="profile-table"><tbody>{(tab==='social'?[['quem sou eu',profile.about],['cidade',profile.city],['país','Brasil'],['idiomas','Português'],['interesses','amizades, comunidades, nostalgia']]:tab==='profissional'?[['atividade','Internet e tecnologia'],['profissão',''],['empresa','']]:[['aniversário',''],['música','Anos 2000'],['filmes',''],['livros','']]).map(([k,v])=><tr key={k}><td>{k}:</td><td>{v||'não informado'}</td></tr>)}</tbody></table></Box><Box title="depoimentos"><div className="listline">“Amizade de verdade dura até depois que a internet cai!” — Mariana</div></Box></>}
{where==='scraps'&&<><div className="mainhead"><h1>meus recados ({scraps.length})</h1><p>Deixe um recado no meu livro de visitas.</p></div><Box title="escrever recado"><div className="small-pad"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Escreva seu scrap..." maxLength={1000}/><button className="submit" onClick={postScrap}>enviar recado</button></div></Box><Box title="recados recebidos">{scraps.map(s=><div className="scrap-row" key={s.id}><Portrait name={s.from}/><div><b>{s.from}</b><p>{s.body}</p></div></div>)}</Box></>}
{where==='friends'&&<><div className="mainhead"><h1>meus amigos (128)</h1><p>Amigos de ontem e de hoje.</p></div><Box title="lista de amigos"><div className="friend-list">{friendNames.map((n,i)=><div key={n}><Portrait name={n}/><div><b><A to={'/profile/'+i}>{n}</A></b><small>adicionado aos amigos</small><A to="/scraps">deixar recado</A></div></div>)}</div></Box></>}
{where==='testimonials'&&<><div className="mainhead"><h1>depoimentos</h1><p>Mensagens que merecem ficar para sempre.</p></div><Box title="depoimentos recebidos"><div className="scrap-row"><Portrait name="Mariana Oliveira"/><div><b>Mariana Oliveira</b><p>Você é uma daquelas pessoas que tornam a vida mais divertida! 💙</p></div></div></Box><Box title="aprovação"><p className="small-pad">Os depoimentos enviados pelos seus amigos aparecerão aqui para aprovação quando a rede estiver conectada ao banco de dados.</p></Box></>}
{where==='photos'&&<><div className="mainhead"><h1>meus álbuns</h1></div><Box title="álbuns de fotos"><div className="albums"><div>📷<p>Meu primeiro álbum</p><small>0 fotos</small></div></div><p className="small-pad">Upload de fotos disponível em uma próxima etapa.</p></Box></>}
{where==='settings'&&<><div className="mainhead"><h1>editar perfil</h1><p>Suas informações pessoais.</p></div><Box title="perfil | social | pessoal"><div className="editform"><label>nome<input value={profile.name} maxLength={60} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label>cidade<input value={profile.city} onChange={e=>setProfile(p=>({...p,city:e.target.value}))}/></label><label>quem sou eu<textarea value={profile.about} onChange={e=>setProfile(p=>({...p,about:e.target.value}))}/></label><span>Alterações salvas automaticamente neste navegador.</span></div></Box></>}
{where==='communities'&&!cid&&<><div className="mainhead"><h1>comunidades</h1><p>Encontre sua turma e converse sobre tudo.</p></div><Box title="buscar comunidades"><div className="small-pad"><input placeholder="Nome da comunidade" value={search} onChange={e=>setSearch(e.target.value)}/></div></Box><Box title="comunidades"><div className="community-list">{cs.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} onClick={()=>go('/communities/'+c.id)}><span className="community-avatar">{c.name.slice(0,2)}</span><span><b>{c.name}</b><small>{c.category} · {c.members.toLocaleString('pt-BR')} membros</small><span>{c.about}</span></span></button>)}</div></Box><Box title="criar uma comunidade"><div className="editform"><label>nome da comunidade<input value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>descrição<textarea value={newAbout} onChange={e=>setNewAbout(e.target.value)}/></label><button className="submit" onClick={createCommunity}>criar comunidade</button></div></Box></>}
{where==='communities'&&community&&<><div className="mainhead"><h1>{community.name}</h1><p>comunidades » {community.category}</p></div><Box title="sobre esta comunidade"><div className="community-detail"><span className="community-avatar big">{community.name.slice(0,2)}</span><div><p>{community.about}</p><p><b>categoria:</b> {community.category}<br/><b>membros:</b> {community.members.toLocaleString('pt-BR')}<br/><b>idioma:</b> português</p><button className="submit" onClick={()=>setJoined(j=>j.includes(community.id)?j.filter(x=>x!==community.id):[...j,community.id])}>{joined.includes(community.id)?'sair da comunidade':'participar da comunidade'}</button></div></div></Box>{parts[2]==='topic'&&topic?<><Box title={'fórum » '+topic.title}><div className="scrap-row"><Portrait name={topic.author}/><div><b>{topic.author}</b><p>{topic.title}</p></div></div>{topic.replies.map((reply,i)=><div className="scrap-row" key={i}><Portrait name={'Membro '+(i+1)}/><div><b>Membro {i+1}</b><p>{reply}</p></div></div>)}</Box><Box title="responder ao tópico"><div className="small-pad"><textarea value={draft} onChange={e=>setDraft(e.target.value)}/><button className="submit" onClick={()=>{if(!draft.trim())return;setTs(all=>all.map(t=>t.id===topic.id?{...t,replies:[...t.replies,draft.trim()]}:t));setDraft('')}}>responder</button></div></Box><p><A to={'/communities/'+community.id}>« voltar ao fórum</A></p></>:<><Box title="fórum da comunidade"><div className="forum-head"><span>tópico</span><span>autor</span><span>respostas</span></div>{ts.filter(t=>t.community===cid).map(t=><div className="forum-line" key={t.id}><A to={'/communities/'+cid+'/topic/'+t.id}>{t.title}</A><span>{t.author}</span><span>{t.replies.length}</span></div>)}</Box><Box title="novo tópico"><div className="small-pad"><input value={topicTitle} onChange={e=>setTopicTitle(e.target.value)} placeholder="Assunto do novo tópico"/><button className="submit" onClick={createTopic}>criar tópico</button></div></Box></>}</>}
</main><aside className="rightcol"><Box title="meus amigos (128)" more={<A to="/friends">ver todos »</A>}>{people}</Box><Box title={'minhas comunidades ('+joined.length+')'} more={<A to="/communities">ver todas »</A>}>{smallCs}</Box><Box title="visitantes recentes"><p className="small-pad">👀 14 visitas nesta semana</p></Box></aside></div><footer>iogurte © 2026 · uma homenagem à internet dos anos 2000 · protótipo demonstrativo</footer></>}
