'use client';
import {useEffect,useState} from 'react';
type Community={id:number;name:string;desc:string;emoji:string;members:number};
type Topic={id:number;community:number;title:string;author:string};
type Scrap={id:number;name:string;text:string};
const seed:Community[]=[{id:1,name:'Eu amo os anos 2000',desc:'Nostalgia pura: MSN, Orkut e lan house!',emoji:'💿',members:15842},{id:2,name:'Odeio acordar cedo',desc:'Só mais cinco minutinhos...',emoji:'😴',members:9842},{id:3,name:'Internet discada',desc:'Quem lembra do som do modem?',emoji:'💻',members:7231},{id:4,name:'Música boa não tem idade',desc:'Do CD ao streaming.',emoji:'🎧',members:12608},{id:5,name:'Saudades das lan houses',desc:'CS 1.6 e muito mais.',emoji:'🎮',members:4620}];
const starterTopics:Topic[]=[{id:1,community:1,title:'Qual era o seu nick no MSN?',author:'Mariana'},{id:2,community:1,title:'Qual era a música do seu perfil?',author:'Rafael'},{id:3,community:3,title:'Quem lembra do barulho do modem?',author:'Bruno'}];
const starterScraps:Scrap[]=[{id:1,name:'Mariana Oliveira',text:'Passando pra deixar um oi! 💜'},{id:2,name:'Rafael Costa',text:'Depois passa no meu perfil 😄'}];
const friendNames=['Mariana Oliveira','Rafael Costa','Ana Beatriz','Bruno Lima','Juliana Martins','Lucas Santos'];
type Tab='Início'|'Comunidades'|'Amigos'|'Recados'|'Depoimentos';
export default function Iogurte(){
 const [tab,setTab]=useState<Tab>('Início'),[communities,setCommunities]=useState(seed),[topics,setTopics]=useState(starterTopics),[scraps,setScraps]=useState(starterScraps),[joined,setJoined]=useState<number[]>([1,3,4]),[selected,setSelected]=useState<number|null>(null),[search,setSearch]=useState(''),[title,setTitle]=useState(''),[desc,setDesc]=useState(''),[topic,setTopic]=useState(''),[scrap,setScrap]=useState(''),[modal,setModal]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem('iogurte-demo')||'null');if(d){setCommunities(d.communities||seed);setTopics(d.topics||starterTopics);setScraps(d.scraps||starterScraps);setJoined(d.joined||[1,3,4]);}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('iogurte-demo',JSON.stringify({communities,topics,scraps,joined}))},[ready,communities,topics,scraps,joined]);
 const go=(t:Tab)=>{setTab(t);setSelected(null)};
 const chosen=communities.find(c=>c.id===selected);
 const openCommunity=(id:number)=>{setTab('Comunidades');setSelected(id)};
 const makeCommunity=()=>{if(!title.trim())return;const id=Date.now();setCommunities(v=>[{id,name:title.trim(),desc:desc.trim()||'Uma nova comunidade!',emoji:'💜',members:1},...v]);setJoined(v=>[...v,id]);setModal(false);setTitle('');setDesc('');openCommunity(id)};
 const makeTopic=()=>{if(!selected||!topic.trim())return;setTopics(v=>[{id:Date.now(),community:selected,title:topic.trim(),author:'Você'},...v]);setTopic('')};
 const makeScrap=()=>{if(!scrap.trim())return;setScraps(v=>[{id:Date.now(),name:'Você',text:scrap.trim()},...v]);setScrap('')};
 const card=(c:Community)=><button className="community" key={c.id} onClick={()=>openCommunity(c.id)}><span className="emoji">{c.emoji}</span><b>{c.name}</b><small>{c.desc}</small><span className="foot">👥 {c.members.toLocaleString('pt-BR')} membros {joined.includes(c.id)?'· ✓ membro':''}</span></button>;
 return <><header><div className="header"><button className="brand" onClick={()=>go('Início')}>iogurte<span>✳</span></button><nav>{(['Início','Comunidades','Amigos'] as Tab[]).map(t=><button key={t} onClick={()=>go(t)} className={tab===t?'active':''}>{t}</button>)}</nav><span className="beta">BETA · DEMONSTRAÇÃO</span><span className="avatar">EU</span></div></header>
 <div className="layout"><aside><section className="panel me"><div className="cover">✦ ✧ ✳</div><span className="portrait">EU</span><h2>Meu perfil</h2><p>Explorando o iogurte ✨</p><div className="stats"><span>amigos <b>128</b></span><span>comunidades <b>{joined.length}</b></span><span>recados <b>{scraps.length}</b></span></div><p>😊 confiável<br/>💙 legal<br/>❤️ sexy</p></section><section className="panel menu">{(['Início','Comunidades','Amigos','Recados','Depoimentos'] as Tab[]).map(t=><button key={t} onClick={()=>go(t)} className={tab===t?'active':''}>♡ &nbsp;{t}</button>)}</section></aside>
 <main>{tab==='Início'&&<><section className="panel welcome"><span className="eyebrow">BEM-VINDO DE VOLTA</span><h1>Que bom te ver por aqui! 👋</h1><p>Suas comunidades e as boas conversas estão esperando por você.</p></section><section className="panel lucky"><b>✨ Sorte de hoje</b><p>As melhores conexões são aquelas que a gente nunca esquece.</p></section><div className="section-title"><h2>Suas comunidades 💜</h2><button onClick={()=>go('Comunidades')}>Ver todas →</button></div><div className="communities">{communities.filter(c=>joined.includes(c.id)).slice(0,4).map(card)}</div><div className="section-title"><h2>Discussões em alta 🔥</h2></div><section className="panel">{topics.slice(0,5).map(t=><button className="topic" key={t.id} onClick={()=>openCommunity(t.community)}><b>💬 {t.title}</b><small>por {t.author} · {communities.find(c=>c.id===t.community)?.name}</small></button>)}</section></>}
 {tab==='Comunidades'&&<><div className="heading"><div><span className="eyebrow">ENCONTRE SUA TURMA</span><h1>Comunidades</h1><p>Um lugar para encontrar quem gosta das mesmas coisas.</p></div><button className="primary" onClick={()=>setModal(true)}>+ Criar comunidade</button></div>{chosen?<><button className="link" onClick={()=>setSelected(null)}>← Todas as comunidades</button><section className="panel detail"><span className="emoji">{chosen.emoji}</span><div><h2>{chosen.name}</h2><p>{chosen.desc}</p><small>{chosen.members.toLocaleString('pt-BR')} membros</small></div><button className="primary" onClick={()=>setJoined(v=>v.includes(chosen.id)?v.filter(n=>n!==chosen.id):[...v,chosen.id])}>{joined.includes(chosen.id)?'✓ Participando':'+ Participar'}</button></section><section className="panel forum"><h2>Fórum da comunidade</h2><div className="compose"><input maxLength={140} placeholder="Comece uma discussão..." value={topic} onChange={e=>setTopic(e.target.value)} onKeyDown={e=>e.key==='Enter'&&makeTopic()}/><button className="primary" onClick={makeTopic}>Publicar</button></div>{topics.filter(t=>t.community===selected).map(t=><div key={t.id} className="topic"><b>💬 {t.title}</b><small>por {t.author}</small></div>)}</section></>:<><input className="search" placeholder="Buscar comunidades..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="communities">{communities.filter(c=>(c.name+' '+c.desc).toLowerCase().includes(search.toLowerCase())).map(card)}</div></>}</>}
 {tab==='Amigos'&&<><h1>Meus amigos 💙</h1><div className="friends">{friendNames.map((name,i)=><div className="panel friend" key={name}><span className="avatar">{name.split(' ').map(p=>p[0]).join('')}</span><b>{name}</b><button onClick={()=>go('Recados')}>Mandar recado</button></div>)}</div><p className="hint">Amizades ilustrativas nesta versão de demonstração.</p></>}
 {tab==='Recados'&&<><h1>Meus recados ✉️</h1><section className="panel compose-card"><h2>Escreva um scrap</h2><textarea value={scrap} maxLength={1000} onChange={e=>setScrap(e.target.value)} placeholder="Deixe uma mensagem especial..."/><button className="primary" onClick={makeScrap}>Enviar recado</button></section><section className="panel">{scraps.map(s=><div className="scrap" key={s.id}><span className="avatar">{s.name.slice(0,2).toUpperCase()}</span><div><b>{s.name}</b><p>{s.text}</p></div></div>)}</section></>}
 {tab==='Depoimentos'&&<><h1>Depoimentos 💜</h1><section className="panel scrap"><span className="avatar">MO</span><div><b>Mariana Oliveira</b><p>Que bom ter você por perto, mesmo que seja pela internet! 💜</p></div></section><p className="hint">Depoimentos demonstrativos.</p></>}</main>
 <aside className="right"><section className="panel"><h3>Meus amigos</h3><div className="mini-friends">{friendNames.map(n=><button key={n} onClick={()=>go('Amigos')}><span className="avatar">{n.split(' ').map(p=>p[0]).join('')}</span><small>{n.split(' ')[0]}</small></button>)}</div></section><section className="panel"><h3>Descubra comunidades</h3>{communities.filter(c=>!joined.includes(c.id)).slice(0,3).map(c=><button className="suggest" key={c.id} onClick={()=>openCommunity(c.id)}>{c.emoji} &nbsp; {c.name} →</button>)}</section><section className="panel nostalgia"><b>💌 Saudades do Orkut?</b><p>O iogurte nasceu para trazer de volta o lado divertido de estar online.</p></section><small className="hint">iogurte © 2026 · demo local</small></aside></div>
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setModal(false)}}><div className="panel modal"><button className="close" onClick={()=>setModal(false)}>✕</button><h2>Nova comunidade 💜</h2><label>Nome<input maxLength={70} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Eu amo sexta-feira"/></label><label>Descrição<textarea maxLength={250} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Do que vamos conversar?"/></label><button className="primary" onClick={makeCommunity}>Criar comunidade</button></div></div>}</>
}